@startuml
start
split
:#Kunde med login;
  :logger ind;
  :Vælg cupcake;
  :vælg ingredienser & antal;
  :føj til kurv;
  :indkøbskurv;
  :betal;
  #pink:error (payment not found);
  stop
  split again
:#kunde uden login;
  :opretter bruger;
  :log ind;
  :Vælg cupcake;
  :vælg ingredienser & antal;
  :føj til kurv;
  :indkøbskurv;
  :betal;
  #pink:error (payment not found);
stop
@enduml